appname = casdoor
httpport = 8000
runmode = prod

sessionOn = true

copyRequestBody = true
driverName = postgres
dataSourceName = "postgres://postgres:postgres@postgres:5432/casdoor?sslmode=disable"
dbName = casdoor

tableNamePrefix = ""

showSql = false

redisEndpoint =
redisPassword =
redisDatabase =

isCloudIntranet = false
authState = "Casdoor-OAuth"

pageSize = 20

storageProvider = "local"
saFile = "/conf/sa.json"

logLevel = "info"
