export const GAME_CONSTANTS = {
  MIN_PLAYERS_TO_START: 2,
  MAX_PLAYERS: 12,
  DEFAULT_BUNKER_CAPACITY_RATIO: 0.4,
} as const;

export const BUNKER_RESOURCES = {
  FOOD_PER_PERSON: 30,
  WATER_PER_PERSON: 30,
  MEDICINE_PER_PERSON: 10,
  DEFAULT_POWER: 100,
} as const;
